name: Run CI checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npx eslint ./
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
